FIX REGRESSION: NoMethodError (undefined method `runtime' Binding)
broken when changing retuirn type of Divisible#transformed_to in 3d1471d7be119ee9ec5f0664a4f6b58a521258af

Signed-off-by: Mark Ratjens <mark@ratjens.com>